### ISSUE TITLE
src/pages/trade/childcomponents/TradeBoardPage.tsx

### ISSUE THREAD

**Issue by kendginwff** [sun0x00/RedTorch-Web-React#3]
<Dropdown label="成交量类型"
                                        styles={{ root: { marginTop: 133 } }}
                                        defaultSelectedKey={tradeActionStore.volumeCondition}
                                        options={
                                            [
                                                { key: VolumeConditionEnum.VC_AV, text: 'AV(任何数量)' },
                                                { key: VolumeConditionEnum.VC_MV, text: 'MV(最小数量)' },
                                                { key: VolumeConditionEnum.VC_AV, text: 'CV(全部数量)' }
                                            ]
                                        }
                                        onChange={(event: any, option?: IDropdownOption, index?: number, value?: number) => {
                                            if (option) {
                                                tradeActionStore.setVolumeCondition(option.key)
                                            }
                                        }}
                                    />

以下对应关系应该是错误的：

key: VolumeConditionEnum.VC_AV, text: 'CV(全部数量)

应该为：
key: VolumeConditionEnum.VC_CV, text: 'CV(全部数量)

**Comment by sun0x00** [comment]
确认是个错误，待下次更新CTP接口新封装版本的时候修正。
